# Generated by Django 5.1.3 on 2024-11-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('transcription_type', models.CharField(choices=[('youtube', 'YouTube'), ('whisper_local', 'Whisper Local'), ('whisper_remote', 'Whisper Remote')], max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('confidence', models.FloatField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_words', to='transcription_api.transcription')),
            ],
        ),
    ]
